version: '3.8'

services:
  odysseia-protect:
    build: .
    container_name: odysseia-protect
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data

volumes:
  data: